#!/bin/bash

CLUSTER_ENV=$1
CLUSTER=$2

echo $CLUSTER | tsh-login-dev >> /dev/null

case $CLUSTER_ENV in

  DEV | UAT)
  case $CLUSTER in

    IC)
    kubectl config use-context gateway.incharge.network-k8s-dev-cluster
    ;;

    NAM)
    kubectl config use-context gateway.nam.asset.e-mobility.abb.com-k8s-abbus-dev-cluster
    ;;
  esac
  ;;

  PROD)
  case $CLUSTER in

    IC)
    kubectl config use-context gateway.incharge.network-k8s-prod-cluster
    tsh requests ls
    echo -n "Enter request-id: "
    read REQUEST_ID
    tsh login --request-id=$REQUEST_ID
    ;;

    NAM)
    kubectl config use-context gateway.nam.asset.e-mobility.abb.com-k8s-abbus-prod-cluster
    tsh requests ls
    echo -n "Enter request-id: "
    read REQUEST_ID
    tsh login --request-id=$REQUEST_ID
    ;;

    ERC)
    kubectl config use-context gateway.erc.asset.e-mobility.abb.com-k8s-abberc-prod-cluster
    tsh requests ls
    echo -n "Enter request-id: "
    read REQUEST_ID
    tsh login --request-id=$REQUEST_ID
    ;;
  esac
  ;;
esac
