#!/bin/bash

function infer_service {
  PREFIX=$(echo $1 | cut -d- -f1)

  case $PREFIX in

    backend)
      SERVICE="BE"
    ;;

    device)
      SERVICE="DM"
    ;;

  esac
}

echo -n "Enter environment name [DEV, UAT, PROD]: "
read CLUSTER_ENV

case $CLUSTER_ENV in

  DEV | UAT)
  echo -n "Enter cluster name [IC, NAM]: "
  read CLUSTER
  ;;

  PROD)
  echo -n "Enter cluster name [IC, NAM, ERC]: "
  read CLUSTER
  ;;
esac

k8s-switch-context $CLUSTER_ENV $CLUSTER

case $CLUSTER_ENV in

  DEV)

  kubectl -n evse-dev get po
  echo -n "Enter pod name: "
  read POD

  infer_service $POD

  case $SERVICE in

    BE)
    kubectl -n evse-dev exec -it $POD -- bin/evse_backend remote
    ;;

    DM)
    kubectl -n evse-dev exec -it $POD -- bin/evdm remote
    ;;
  esac

  ;;


  UAT)

  kubectl -n evse-uat get po
  echo -n "Enter pod name: "
  read POD

  infer_service $POD

  case $SERVICE in

    BE)
    kubectl -n evse-uat exec -it $POD -- bin/evse_backend remote
    ;;

    DM)
    kubectl -n evse-uat exec -it $POD -- bin/evdm remote
    ;;
  esac

  ;;

  PROD)

  kubectl -n evse-prod get po
  echo -n "Enter pod name: "
  read POD

  infer_service $POD

  case $SERVICE in

    BE)
    kubectl -n evse-prod exec -it $POD -- bin/evse_backend remote
    ;;

    DM)
    kubectl -n evse-prod exec -it $POD -- bin/evdm remote
    ;;
  esac

  ;;

esac
