#!/bin/bash

echo -n "Enter cluster name [IC, NAM, ERC]: "
read CLUSTER

case $CLUSTER in

  IC)
  echo "Logging in IC cluster..."

  tsh login --proxy=gateway.incharge.network:443 --auth=passwordless --user=vlado.p gateway.incharge.network

  echo "Log in finished!"
  ;;

  NAM)
  echo "Logging in NAM cluster..."

  tsh login --proxy=gateway.nam.asset.e-mobility.abb.com:443 --auth=passwordless --user=vlado.p gateway.nam.asset.e-mobility.abb.com

  echo "Log in finished!"
  ;;

  ERC)
  echo "Logging in ERC cluster..."

  tsh login --proxy=gateway.erc.asset.e-mobility.abb.com:443 --auth=passwordless --user=vlado.p gateway.erc.asset.e-mobility.abb.com

  echo "Log in finished!"
  ;;

  *)
  echo "Invalid cluster"
  ;;
esac
